"use client";

//import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import ClientNavbar from "./navbar/clientNavbar";
import { store } from "@/store";
import { usePathname } from "next/navigation";
// import store from "@/store";

// // Define the Inter font loader at the top level
// const inter = Inter({ subsets: ["latin"] });

// // Metadata for the app (if needed)
// export const metadata = {
//   title: "Skill Capital",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Get the current route

  // Check if the current page is not the login page
  const isLoginPage = pathname === "/login";
  return (
    <html lang="en">
      <head>
        <title>Skill Capital</title>
      </head>
      <body>
        <Provider store={store}>
          <ClientNavbar />
          {!isLoginPage && <ClientNavbar />}
          
          {/* Apply padding only if it's not the login page */}
          <div className={isLoginPage ? "" : "pt-16"}>
          {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
